// <auto-generated />
using System;
using Database.Picking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Picking.Migrations
{
    [DbContext(typeof(PickingDbContext))]
    partial class PickingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Database.Picking.Entities.OrderPickingDetailEntity", b =>
                {
                    b.Property<string>("OrderPicking_Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("varchar(511)");

                    b.HasKey("OrderPicking_Id", "Name");

                    b.ToTable("Picking.OrderPickingDetail");
                });

            modelBuilder.Entity("Database.Picking.Entities.OrderPickingEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Picking.OrderPicking");
                });

            modelBuilder.Entity("Database.Picking.Entities.PickingItemDetailEntity", b =>
                {
                    b.Property<string>("PickingItem_Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("varchar(511)");

                    b.HasKey("PickingItem_Id", "Name");

                    b.ToTable("Picking.PickingItemDetail");
                });

            modelBuilder.Entity("Database.Picking.Entities.PickingItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OrderPicking_Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderPicking_Id");

                    b.ToTable("Picking.PickingItem");
                });

            modelBuilder.Entity("Database.Picking.Entities.OrderPickingDetailEntity", b =>
                {
                    b.HasOne("Database.Picking.Entities.OrderPickingEntity", "OrderPicking")
                        .WithMany("Details")
                        .HasForeignKey("OrderPicking_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderPicking");
                });

            modelBuilder.Entity("Database.Picking.Entities.PickingItemDetailEntity", b =>
                {
                    b.HasOne("Database.Picking.Entities.PickingItemEntity", "PickingItem")
                        .WithMany("Details")
                        .HasForeignKey("PickingItem_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickingItem");
                });

            modelBuilder.Entity("Database.Picking.Entities.PickingItemEntity", b =>
                {
                    b.HasOne("Database.Picking.Entities.OrderPickingEntity", "OrderPicking")
                        .WithMany("Items")
                        .HasForeignKey("OrderPicking_Id");

                    b.Navigation("OrderPicking");
                });

            modelBuilder.Entity("Database.Picking.Entities.OrderPickingEntity", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Database.Picking.Entities.PickingItemEntity", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
